import type { Metadata } from "next";
import { Baloo_Bhai_2 } from "next/font/google";
import "./globals.css";

const font = Baloo_Bhai_2({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin-ext"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={`${font.className}`}>
        {children}
      </body>
    </html>
  );
}
